name: Build
on:
  push:
    branches: [ "main", "release1x", "release" ]
    tags: [ "v*"]
  pull_request:
    branches: [ "main", "release1x", "release" ]
env:
  OPENTAP_ANSI_COLORS: true
  OPENTAP_NO_UPDATE_CHECK: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on:
       group: OpenTAP-SpokeVPC
       labels:  [Linux, X64]
    container: ghcr.io/opentap/oci-images/build-dotnet:latest
    env:
      KS8500_REPO_TOKEN: ${{ secrets.KS8500_REPO_TOKEN }}
      TAP_SIGN_ADDRESS: ${{ secrets.TAP_SIGN_ADDRESS_INTERNAL }}
      TAP_SIGN_AUTH:  ${{ secrets.TAP_SIGN_AUTH }}
      TAP_SIGN_CERT: ${{ github.workspace }}/sign.cer
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Fix tags
      if: startsWith(github.ref, 'refs/tags/v')
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build
      run: dotnet build --no-restore -c Release
    
    - name: Package Expressions
      working-directory: bin/Release
      run: ./tap package create ../../OpenTap.BasicMixins/package.xml

    - name: Run Unit Tests
      working-directory: bin/Release
      run: ./tap unit-test run

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: TapPackage
        retention-days: 14
        path: |
          bin/Release/*.TapPackage

  publish:
    environment: packages.opentap.io
    runs-on:
      group: OpenTAP-SpokeVPC
      labels:  [Linux, X64]
    container: ghcr.io/opentap/oci-images/build-dotnet:latest
    needs: build
    steps:
    - name: Download binaries
      uses: actions/download-artifact@v4
      with:
        name: TapPackage
        path: package

    - name: Setup OpenTAP
      uses: opentap/setup-opentap@main
      with:
        version: 9.23.0
        packages: 'Repository Client:beta'

    - name: Publish Packages
      working-directory: package
      run: |
        tap repo upload --repository http://packages.opentap.io --token ${{ secrets.REPO_TOKEN }} "Basic Mixins".*.TapPackage
      
